#!/bin/bash
# /etc/init.d/botd

### BEGIN INIT INFO
# Provides:          botd
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Bot module
# Description:       This service is to run a bot module that connects to a skybot server.
### END INIT INFO


case "$1" in 
    start)
        echo "Starting Bot"
        node /home/pi/codes/bot_module/bot.js &
        ;;
    stop)
        echo "Stopping Bot"
        kill $(ps aux | grep "bot.js" | grep -v "grep" | awk '{print $2}')
        ;;
    *)
        echo "Usage: /etc/init.d/botd start|stop"
        exit 1
        ;;
esac

exit 0
